In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
a=np.array([1.1,2.2,3.3,4.4,5.5,6.6,7.7])
print(np.round(a))

[1. 2. 3. 4. 6. 7. 8.]


In [ ]:
a=np.array([1.1,2.2,3.3,4.4,5.5,6.6,7.7])
print(np.rint(a))

[1. 2. 3. 4. 6. 7. 8.]


In [ ]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,0])
print(np.true_divide(a,b))

[0.16666667 0.28571429 0.375      0.44444444        inf]


<ipython-input-14-f06a3f14835f>:3: RuntimeWarning: divide by zero encountered in divide
  print(np.true_divide(a,b))


In [ ]:

b=np.array([6,7,8,9,0])
print(np.union1d(a,b))

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
a=np.array([1,2,3,444,55,55,666,666])
print(np.unique(a))

[  1   2   3  55 444 666]


In [ ]:
zeros_arr = np.zeros((3,3), dtype=int)
print(zeros_arr)
ones_arr = np.ones((0,2),dtype=int)
print(ones_arr)

arange_arr = np.arange(10)
print(arange_arr)
reshaped_arr = arr.reshape(5,1)
print(reshaped_arr)
sliced_arr = arr[2:4]
print(sliced_arr)
a=np.array([1,2,3,4,5,6,7,8])
b=a.T
print(b)
b=np.split(a,4)
print(b)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[]
[0 1 2 3 4 5 6 7 8 9]
[[1]
 [2]
 [3]
 [4]
 [5]]
[3 4]
[1 2 3 4 5 6 7 8]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [ ]:
arange_arr=np.arange(0,100,5)
print(arange_arr)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [ ]:
a=np.arange(0,30)
a.reshape(2,3,5)
print(np.dstack((a)))

[[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22
   23 24 25 26 27 28 29]]]


In [ ]:
a=int(5)
print(a)

5


In [ ]:
a=np.arange(

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a*b)
print(a@b)
c=np.dot(a,b)

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [ ]:
arange_arr=np.arange(0,1000,5)
print(arange_arr)
d=np.savetxt("/content/drive/Mydrive/dataset/csp.txt",arange_arr)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175
 180 185 190 195 200 205 210 215 220 225 230 235 240 245 250 255 260 265
 270 275 280 285 290 295 300 305 310 315 320 325 330 335 340 345 350 355
 360 365 370 375 380 385 390 395 400 405 410 415 420 425 430 435 440 445
 450 455 460 465 470 475 480 485 490 495 500 505 510 515 520 525 530 535
 540 545 550 555 560 565 570 575 580 585 590 595 600 605 610 615 620 625
 630 635 640 645 650 655 660 665 670 675 680 685 690 695 700 705 710 715
 720 725 730 735 740 745 750 755 760 765 770 775 780 785 790 795 800 805
 810 815 820 825 830 835 840 845 850 855 860 865 870 875 880 885 890 895
 900 905 910 915 920 925 930 935 940 945 950 955 960 965 970 975 980 985
 990 995]


FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/Mydrive/dataset/csp.txt'

In [ ]:
a=np.random.rand()
print(a)
b=np.random.randint(2,3)
print(b)

0.309014793315217
2


In [ ]:
a=np.array([[1,2],[3,4]])
print(a.shape)

(2, 2)


In [ ]:
a=np.array([1,2,3,4,5,6])
a.resize(2,3)
b=np.array([21,233,23,33,345,55])
b.resize(2,3)
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[  1   2   3]
 [  4   5   6]
 [ 21 233  23]
 [ 33 345  55]]
[[  1   2   3  21 233  23]
 [  4   5   6  33 345  55]]


In [ ]:
import numpy as np
a1=np.eye(4)
print(a1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
a1=np.full((2,2),3)
print(a1)
print(a1.itemsize)
x=[1,2,3]
a=np.asarray(x)
print(a)
print(type(a))

[[3 3]
 [3 3]]
8
[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
x=np.array([1,4,0],float)
y=np.array([2,2,1],float)
print(np.inner(x,y))
print(np.outer(x,y))
print(np.cross(x,y))

10.0
[[2. 2. 1.]
 [8. 8. 4.]
 [0. 0. 0.]]
[ 4. -1. -6.]


In [ ]:
frombuffer numpy import random
a=np.ones((2,2),dtype=int)
print(a.min(axis=1))

In [ ]:
a=np.linspace(0.8,2,5)
print(a)

[0.8 1.1 1.4 1.7 2. ]


In [ ]:
a=np.arange(24).reshape(4,6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [ ]:
from numpy import random
a=np.ones((2,3),dtype=int)
print(a.sum(axis=1))

[3 3]


In [ ]:
frombuffer numpy import random
a=np.ones((2,2),dtype=int)
print(a.min(axis=1))

[1 1]


In [ ]:
from numpy import random
a=np.ones((2,2),dtype=int)
print(a.cumsum(axis=0))

[[1 1]
 [2 2]]


In [ ]:
a=np.ceil(np.random.random((2,2)))
c=np.ceil(np.random.random((2,2)))
print(a)
print(c)

[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]


number of rows become group
column become row
number of coulumns becomes group






In [ ]:
a=np.array([30])


In [ ]:
a=np.array([30])
a.reshape(2,3)

AttributeError: module 'numpy' has no attribute 'arange_arr'

number of rows become number of group
column becomes rows
group become column

In [ ]:
data= np.loadtxt("/content/csp.txt",dtype=int)
d=np.savetxt("/content/date.txt", data)
print(d)
print(data)

None
[  123   444  5556 78666   444]


10.0
-0.8011526357338304


In [ ]:
a=np.array([10,20,30,40,50])
b=np.array([2,3,34,55,55])
c=np.multiply(a,b)
print(c)

[  20   60 1020 2200 2750]


In [ ]:
from numpy import random
x=random.normal(loc=1,scale=2,size=(2,3))
print(x)


[[ 0.7427738  -0.90314812 -0.35565542]
 [-0.62088361 -2.45745413 -1.03983501]]


In [ ]:
x=random.binomial(n=12,p=0.5,size=10)
print(x)

[ 6  5  7  6  6  6  6  9 10  4]


In [ ]:
x=random.poisson(lam=2,size=10)
print(x)

[0 1 2 2 2 3 1 1 4 2]


In [ ]:
x=random.choice([3,5],p=[0.5,0.5],size=(3,5))
print(x)


[[3 5 5 3 3]
 [5 5 3 3 5]
 [5 5 5 3 5]]
